/* MLton 20130715 (built Mon Jun 13 11:54:01 AEST 2016 on ports.extensibl.com) */
/*   created this file on Mon Jun 13 12:11:05 2016. */
/* Do not edit this file. */
/* Flag settings:  */
/*    align: 8 */
/*    atMLtons: (mlton-compile, @MLton, --) */
/*    chunk: chunk per function */
/*    closureConvertGlobalize: true */
/*    closureConvertShrink: true */
/*    codegen: amd64 */
/*    contifyIntoMain: false */
/*    debug: false */
/*    defaultChar: char8 */
/*    defaultWideChar: widechar32 */
/*    defaultInt: int32 */
/*    defaultReal: real64 */
/*    defaultWord: word32 */
/*    diag passes: [] */
/*    drop passes: [] */
/*    elaborate allowConstant (default): false */
/*    elaborate allowConstant (enabled): true */
/*    elaborate allowFFI (default): false */
/*    elaborate allowFFI (enabled): true */
/*    elaborate allowPrim (default): false */
/*    elaborate allowPrim (enabled): true */
/*    elaborate allowOverload (default): false */
/*    elaborate allowOverload (enabled): true */
/*    elaborate allowRebindEquals (default): false */
/*    elaborate allowRebindEquals (enabled): true */
/*    elaborate deadCode (default): false */
/*    elaborate deadCode (enabled): true */
/*    elaborate forceUsed (default): false */
/*    elaborate forceUsed (enabled): true */
/*    elaborate ffiStr (default):  */
/*    elaborate ffiStr (enabled): true */
/*    elaborate nonexhaustiveExnMatch (default): default */
/*    elaborate nonexhaustiveExnMatch (enabled): true */
/*    elaborate nonexhaustiveMatch (default): warn */
/*    elaborate nonexhaustiveMatch (enabled): true */
/*    elaborate redundantMatch (default): warn */
/*    elaborate redundantMatch (enabled): true */
/*    elaborate resolveScope (default): strdec */
/*    elaborate resolveScope (enabled): true */
/*    elaborate sequenceNonUnit (default): warn */
/*    elaborate sequenceNonUnit (enabled): true */
/*    elaborate warnUnused (default): true */
/*    elaborate warnUnused (enabled): true */
/*    elaborate only: false */
/*    emit main: true */
/*    export header: None */
/*    exn history: false */
/*    generated output format: executable */
/*    gc check: Limit */
/*    indentation: 3 */
/*    inlineIntoMain: true */
/*    inlineLeafA: {loops = true, repeat = true, size = Some 20} */
/*    inlineLeafB: {loops = true, repeat = true, size = Some 40} */
/*    inlineNonRec: {small = 60, product = 320} */
/*    input file: mlton */
/*    keep CoreML: false */
/*    keep def use: true */
/*    keep dot: false */
/*    keep Machine: false */
/*    keep passes: [] */
/*    keep RSSA: false */
/*    keep SSA: false */
/*    keep SSA2: false */
/*    keep SXML: false */
/*    keep XML: false */
/*    extra_: false */
/*    lib dir: /usr/ports/pobj/mlton-20130715/mlton-on-20130715-release/build/lib */
/*    lib target dir: /usr/ports/pobj/mlton-20130715/mlton-on-20130715-release/build/lib/targets/self */
/*    loop passes: 1 */
/*    mark cards: true */
/*    max function size: 10000 */
/*    mlb path vars: [{var = MLTON_ROOT, path = $(LIB_MLTON_DIR)/sml}, {var = SML_LIB, path = $(LIB_MLTON_DIR)/sml}] */
/*    native commented: 0 */
/*    native live stack: false */
/*    native optimize: 1 */
/*    native move hoist: true */
/*    native copy prop: true */
/*    native copy prop cutoff: 1000 */
/*    native cutoff: 100 */
/*    native live transfer: 8 */
/*    native shuffle: true */
/*    native ieee fp: false */
/*    native split: Some 20000 */
/*    optimizationPasses: [<ssa2::default>, <ssa::default>, <sxml::default>, <xml::default>] */
/*    polyvariance: Some {hofo = true, rounds = 2, small = 30, product = 300} */
/*    prefer abs paths: false */
/*    prof passes: [] */
/*    profile: None */
/*    profile branch: false */
/*    profile C: [] */
/*    profile IL: ProfileSource */
/*    profile include/exclude: [(Seq [Star [.], Or [Seq [Seq [[$], [(], [S], [M], [L], [_], [L], [I], [B], [)]]]], Star [.]], false)] */
/*    profile raise: false */
/*    profile stack: false */
/*    profile val: false */
/*    show basis: None */
/*    show def-use: None */
/*    show types: true */
/*    target: self */
/*    target arch: AMD64 */
/*    target OS: OpenBSD */
/*    type check: false */
/*    verbosity: Pass */
/*    warn unrecognized annotation: true */
/*    warn deprecated features: true */
/*    zone cut depth: 100 */
.text
.p2align 0x4
.globl loop_4794
.hidden loop_4794
loop_4794:
L_372899:
	cmpq %rbp,(gcState+0x18)(%rip)
	jnb loop_3750
L_372928:
	movq (c_stackP+0x0)(%rip),%rsp
	movl $0x0,%r15d
	movl %r15d,%edx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x18,%rbp
	leaq (L_372929+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_collect
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_372929
.p2align 0x4
.long 0x45F
L_372929:
	addq $0xFFFFFFFFFFFFFFE8,%rbp
.p2align 0x4,,0x7
loop_3750:
	cmpq %r12,(gcState+0x8)(%rip)
	jb L_530824
.p2align 0x4,,0x7
L_372901:
	movq 0x0(%rbp),%r15
	movl 0x0(%r15),%r14d
	movq 0x8(%r15),%r13
	movq 0x8(%rbp),%r15
	cmpq $0x1,%r15
	je L_530822
	cmpq $0x2,%r15
	je L_530820
L_372902:
	movq 0xFFFFFFFFFFFFFFF8(%r15),%r11
	shrq $0x1,%r11
	cmpq $0xDC1,%r11
	je L_530819
	cmpq $0xDC2,%r11
	je L_530817
	cmpq $0xDC3,%r11
	je L_530815
	cmpq $0xDC4,%r11
	je L_530813
L_372903:
	movq 0x0(%r15),%r15
	movq %r15,0x8(%rbp)
	jmp loop_3750
.p2align 0x4
L_530813:
L_372919:
	incl %r14d
	jo L_530814
L_372921:
	movq $0x14E9,0x0(%r12)
	movq %r12,%r11
	addq $0x8,%r11
	movl %r14d,0x0(%r11)
	movq %r13,0x8(%r11)
	addq $0x18,%r12
	movl $0x0,0x4(%r11)
	movq %r11,0x0(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530814:
L_372920:
	movq $0x3,(globalObjptrNonRoot+0x0)(%rip)
	movq (gcState+0x560)(%rip),%rbp
	addq (gcState+0x20)(%rip),%rbp
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530815:
L_372912:
	movq 0x0(%r15),%r13
	cmpq $0x1,%r13
	je L_530816
L_372913:
	movq 0x8(%r13),%r15
	movq 0x0(%r13),%r13
	movq 0x0(%rbp),%r14
	movq %r15,0x0(%rbp)
	movq %r13,%r15
L_372914:
	movq %r14,0x10(%rbp)
	movq %r15,0x18(%rbp)
	addq $0x10,%rbp
	leaq (L_372915+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	jmp loop_4794
.p2align 0x4
L_530816:
L_372918:
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530817:
L_372905:
	movq 0x0(%r15),%r13
	cmpq $0x1,%r13
	je L_530818
L_372906:
	movq 0x8(%r13),%r15
	movq 0x0(%r13),%r13
	movq 0x0(%rbp),%r14
	movq %r15,0x0(%rbp)
	movq %r13,%r15
L_372907:
	movq %r14,0x10(%rbp)
	movq %r15,0x18(%rbp)
	addq $0x10,%rbp
	leaq (L_372908+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	jmp loop_4794
.p2align 0x4
L_530818:
L_372911:
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530819:
L_372904:
	movq 0x8(%r15),%r11
	movq 0x0(%r15),%r15
	movq %r15,0x8(%rbp)
	movq $0x28CF,0x0(%r12)
	movq %r12,%r15
	addq $0x8,%r15
	movq %r11,0x0(%r15)
	movq %r13,0x8(%r15)
	addq $0x18,%r12
	movq $0x14E9,0x0(%r12)
	movq %r12,%r13
	addq $0x8,%r13
	movl %r14d,0x0(%r13)
	movq %r15,0x8(%r13)
	addq $0x18,%r12
	movl $0x0,0x4(%r13)
	movq %r13,0x0(%rbp)
	jmp loop_3750
.p2align 0x4
L_530820:
L_372924:
	incl %r14d
	jo L_372920
L_372925:
	movq $0x14E9,0x0(%r12)
	movq %r12,%r11
	addq $0x8,%r11
	movl %r14d,0x0(%r11)
	movq %r13,0x8(%r11)
	addq $0x18,%r12
	movl $0x0,0x4(%r11)
	movq %r11,0x0(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530822:
L_372922:
	incl %r14d
	jo L_372920
L_372923:
	movq $0x14E9,0x0(%r12)
	movq %r12,%r11
	addq $0x8,%r11
	movl %r14d,0x0(%r11)
	movq %r13,0x8(%r11)
	addq $0x18,%r12
	movl $0x0,0x4(%r11)
	movq %r11,0x0(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530824:
L_372926:
	movq (c_stackP+0x0)(%rip),%rsp
	movl $0x0,%r15d
	movl %r15d,%edx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x18,%rbp
	leaq (L_372927+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_collect
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_372927
.p2align 0x4
.long 0x45F
L_372927:
	addq $0xFFFFFFFFFFFFFFE8,%rbp
	jmp L_372901
.p2align 0x4
.long 0x4AF
L_372915:
	addq $0xFFFFFFFFFFFFFFF0,%rbp
	movq 0x10(%rbp),%r14
	movq %r14,0x8(%rbp)
	movq 0x0(%rbp),%r13
	cmpq $0x1,%r13
	je L_530825
L_372916:
	movq 0x0(%r13),%r15
	movq 0x8(%r13),%r13
	movq %r13,0x0(%rbp)
	jmp L_372914
.p2align 0x4
L_530825:
L_372917:
	movq %r14,0x0(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
.long 0x4AF
L_372908:
	addq $0xFFFFFFFFFFFFFFF0,%rbp
	movq 0x10(%rbp),%r14
	movq %r14,0x8(%rbp)
	movq 0x0(%rbp),%r13
	cmpq $0x1,%r13
	je L_530826
L_372909:
	movq 0x0(%r13),%r15
	movq 0x8(%r13),%r13
	movq %r13,0x0(%rbp)
	jmp L_372907
.p2align 0x4
L_530826:
L_372910:
	movq %r14,0x0(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.text
.p2align 0x4
.globl loop_4795
.hidden loop_4795
loop_4795:
L_372930:
	cmpq %rbp,(gcState+0x18)(%rip)
	jb L_373226
L_372931:
	cmpq %r12,(gcState+0x8)(%rip)
	jb L_530841
L_372932:
	movq 0x0(%rbp),%r15
	cmpq $0x1,%r15
	je L_530840
	cmpq $0x2,%r15
	je L_530834
L_372933:
	movq 0xFFFFFFFFFFFFFFF8(%r15),%r14
	shrq $0x1,%r14
	cmpq $0xDC1,%r14
	je L_530833
	cmpq $0xDC2,%r14
	je L_530831
	cmpq $0xDC3,%r14
	je L_530829
	cmpq $0xDC4,%r14
	je L_530827
L_372934:
	movq 0x18(%rbp),%r14
	movq %r14,0x48(%rbp)
	movq 0x20(%rbp),%r14
	movq %r14,0x50(%rbp)
	movq 0x28(%rbp),%r14
	movq %r14,0x58(%rbp)
	movq 0x30(%rbp),%r14
	movq %r14,0x60(%rbp)
	movq 0x0(%r15),%r14
	movq %r14,0x30(%rbp)
	movq 0x38(%rbp),%r15
	movq %r15,0x68(%rbp)
	movq 0x40(%rbp),%r15
	movq %r15,0x70(%rbp)
	movl 0x10(%rbp),%r15d
	movl %r15d,0x40(%rbp)
	movq 0x8(%rbp),%r15
	movq %r15,0x38(%rbp)
	addq $0x30,%rbp
	leaq (L_372935+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	jmp loop_4795
.p2align 0x4
L_530827:
L_373197:
	movq 0x0(%r15),%r14
	movq 0x30(%rbp),%r15
	movl 0x0(%r15),%r13d
	incl %r13d
	movl %r13d,0x8(%rbp)
	jo L_530828
L_373199:
	movl %r13d,0x0(%r15)
	movq $0x3D0D,0x0(%r12)
	movq %r12,%r15
	addq $0x8,%r15
	movq %r14,0x10(%r15)
	addq $0x20,%r12
	movl %r13d,0x0(%r15)
	movl $0x0,0x4(%r15)
	movq 0x28(%rbp),%r14
	movq %r14,0x8(%r15)
	movq %r15,0x20(%rbp)
	movl $0x100,0x28(%rbp)
	movl $0x0,0x2C(%rbp)
	addq $0x20,%rbp
	leaq (L_373200+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	jmp fold_0
.p2align 0x4
L_530828:
L_373198:
	movq $0x3,(globalObjptrNonRoot+0x0)(%rip)
	movq (gcState+0x560)(%rip),%rbp
	addq (gcState+0x20)(%rip),%rbp
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530829:
L_373154:
	movq 0x0(%r15),%r14
	cmpq $0x1,%r14
	je L_530830
L_373155:
	movq 0x8(%r14),%r13
	movq %r13,0x48(%rbp)
	movq 0x0(%r14),%r14
	movq $0x1,0x50(%rbp)
	movq 0x18(%rbp),%r13
	movq %r13,0x58(%rbp)
	movq %r13,0x60(%rbp)
	movq %r14,%r15
L_373156:
	movq %r15,0x70(%rbp)
	movq 0x8(%rbp),%r15
	movq %r15,0x78(%rbp)
	movl 0x10(%rbp),%r15d
	movl %r15d,0x80(%rbp)
	movq 0x18(%rbp),%r15
	movq %r15,0x88(%rbp)
	movq 0x20(%rbp),%r15
	movq %r15,0x90(%rbp)
	movq 0x28(%rbp),%r15
	movq %r15,0x98(%rbp)
	movq 0x30(%rbp),%r15
	movq %r15,0xA0(%rbp)
	movq 0x38(%rbp),%r15
	movq %r15,0xA8(%rbp)
	movq 0x40(%rbp),%r15
	movq %r15,0xB0(%rbp)
	addq $0x70,%rbp
	leaq (L_373157+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	jmp loop_4795
.p2align 0x4
L_530830:
L_373196:
	movq $0x1,0x0(%rbp)
	movq 0x18(%rbp),%r15
	movq %r15,0x8(%rbp)
	movq %r15,0x10(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530831:
L_373023:
	movq 0x0(%r15),%r14
	movq (globalObjptr+0xF50)(%rip),%r13
	movq $0xF47,0xFFFFFFFFFFFFFFF8(%r13)
	cmpq $0x1,%r14
	je L_530832
L_373024:
	movq 0x8(%r14),%r11
	movq %r11,0x48(%rbp)
	movq 0x0(%r14),%r14
	movq %r13,0x50(%rbp)
	movq 0x18(%rbp),%r13
	movq %r13,0x58(%rbp)
	movq %r13,0x60(%rbp)
	movq %r14,%r15
L_373025:
	movq %r15,0x70(%rbp)
	movq 0x8(%rbp),%r15
	movq %r15,0x78(%rbp)
	movl 0x10(%rbp),%r15d
	movl %r15d,0x80(%rbp)
	movq 0x18(%rbp),%r15
	movq %r15,0x88(%rbp)
	movq 0x20(%rbp),%r15
	movq %r15,0x90(%rbp)
	movq 0x28(%rbp),%r15
	movq %r15,0x98(%rbp)
	movq 0x30(%rbp),%r15
	movq %r15,0xA0(%rbp)
	movq 0x38(%rbp),%r15
	movq %r15,0xA8(%rbp)
	movq 0x40(%rbp),%r15
	movq %r15,0xB0(%rbp)
	addq $0x70,%rbp
	leaq (L_373026+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	jmp loop_4795
.p2align 0x4
L_530832:
L_373153:
	movq %r13,0x0(%rbp)
	movq 0x18(%rbp),%r15
	movq %r15,0x8(%rbp)
	movq %r15,0x10(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530833:
L_372965:
	movq 0x8(%r15),%r14
	movq %r14,0x48(%rbp)
	movq 0x0(%r15),%r14
	movq %r14,0x58(%rbp)
	movq 0x8(%rbp),%r15
	movq %r15,0x60(%rbp)
	movl 0x10(%rbp),%r15d
	movl %r15d,0x68(%rbp)
	movq 0x18(%rbp),%r15
	movq %r15,0x70(%rbp)
	movq 0x20(%rbp),%r15
	movq %r15,0x78(%rbp)
	movq 0x28(%rbp),%r15
	movq %r15,0x80(%rbp)
	movq 0x30(%rbp),%r15
	movq %r15,0x88(%rbp)
	movq 0x38(%rbp),%r15
	movq %r15,0x90(%rbp)
	movq 0x40(%rbp),%r15
	movq %r15,0x98(%rbp)
	addq $0x58,%rbp
	leaq (L_372966+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	jmp loop_4795
.p2align 0x4
L_530834:
L_373225:
	movq 0x38(%rbp),%r14
	xchgq %r14,%r15
anchor_0:
	movq 0x40(%rbp),%r14
	movq 0x8(%r14),%r13
	movl 0x0(%r14),%r11d
	movl 0x0(%r13),%r14d
	incl %r14d
	movl %r14d,0x48(%rbp)
	jo L_373198
L_373213:
	movl %r14d,0x0(%r13)
	movq 0x0(%r15),%r13
	movq $0x1B59,0x0(%r12)
	movq %r12,%r10
	addq $0x8,%r10
	movq %r13,0x8(%r10)
	addq $0x18,%r12
	movl %r14d,0x0(%r10)
	movl $0x0,0x4(%r10)
	movq %r15,%r14
	shrq $0x8,%r14
	movq (gcState+0x3C8)(%rip),%r13
	movb $0x1,0x0(%r13,%r14,1)
	movq %r10,0x0(%r15)
	movslq %r11d,%rdx
	movq %rdx,0x50(%rbp)
	testq %rdx,%rdx
	jz L_530838
L_373214:
	cmpq $0x7FFFFFFF,%rdx
	ja L_530837
L_373215:
	movq (c_stackP+0x0)(%rip),%rsp
	movq $0xAAB,%rcx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x60,%rbp
	leaq (L_373216+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_arrayAllocate
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373216
.p2align 0x4
.long 0x559B
L_373216:
	addq $0xFFFFFFFFFFFFFFA0,%rbp
	movq %rax,%r15
L_373217:
	xorq %r14,%r14
.p2align 0x4,,0x7
loop_3768:
	cmpq 0x50(%rbp),%r14
	jnl L_530836
L_373219:
	movl %r14d,%r11d
	cmpl %r11d,0x48(%rbp)
	je L_530835
L_373220:
	movq $0x1,%r13
L_373221:
	movq %r15,%r11
	shrq $0x8,%r11
	movq (gcState+0x3C8)(%rip),%r10
	movb $0x1,0x0(%r10,%r11,1)
	movq %r13,0x0(%r15,%r14,8)
	incq %r14
	jmp loop_3768
.p2align 0x4
L_530835:
L_373222:
	movq (globalObjptr+0xF50)(%rip),%r13
	movq $0xF47,0xFFFFFFFFFFFFFFF8(%r13)
	jmp L_373221
.p2align 0x4
L_530836:
L_373218:
	movq $0x191D,0xFFFFFFFFFFFFFFF8(%r15)
	movq %r15,0x8(%rbp)
	movq %r15,0x10(%rbp)
	movq $0x1,0x0(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530837:
L_373007:
	movq $0x5,(globalObjptrNonRoot+0x0)(%rip)
	movq (gcState+0x560)(%rip),%rbp
	addq (gcState+0x20)(%rip),%rbp
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530838:
L_373224:
	movq (globalObjptr+0x1458)(%rip),%r15
	jmp L_373217
.p2align 0x4
L_530840:
L_373212:
	movq 0x8(%rbp),%r14
	xchgq %r14,%r15
	jmp anchor_0
.p2align 0x4
L_530841:
L_373226:
	movq (c_stackP+0x0)(%rip),%rsp
	movl $0x0,%r15d
	movl %r15d,%edx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x50,%rbp
	leaq (L_373227+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_collect
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373227
.p2align 0x4
.long 0x530
L_373227:
	addq $0xFFFFFFFFFFFFFFB0,%rbp
	jmp L_372932
.p2align 0x4
.long 0x459
L_372935:
	addq $0xFFFFFFFFFFFFFFD0,%rbp
	movq 0x30(%rbp),%r15
	movq %r15,0x28(%rbp)
	movq 0x38(%rbp),%r15
	movq %r15,0x30(%rbp)
	movq 0x40(%rbp),%r14
	movq %r14,0x38(%rbp)
	movq 0xFFFFFFFFFFFFFFF0(%r15),%r14
	movl %r14d,%r13d
	movl %r13d,0x40(%rbp)
	movslq %r13d,%r11
	cmpq %r11,%r14
	jne L_372937
L_372938:
	cmpl $0x0,%r13d
	jl L_372962
L_372939:
	movl $0x0,0x28(%rbp)
.p2align 0x4,,0x7
loop_3751:
	movl 0x28(%rbp),%r15d
	cmpl 0x40(%rbp),%r15d
	jnl L_530849
L_372941:
	movslq %r15d,%r14
	movq %r14,0x48(%rbp)
	movq 0x30(%rbp),%r15
	movq 0x0(%r15,%r14,8),%r13
	movq %r13,0x50(%rbp)
	cmpq $0x1,%r13
	je L_372947
L_372942:
	movq 0x38(%rbp),%r15
	movq 0xFFFFFFFFFFFFFFF0(%r15),%r14
	movl %r14d,%r13d
	movl %r13d,0x2C(%rbp)
	movslq %r13d,%r11
	cmpq %r11,%r14
	jne L_530847
L_372944:
	cmpl $0x0,%r13d
	jl L_530846
L_372945:
	movl $0x0,0x44(%rbp)
loop_3752:
	movl 0x44(%rbp),%r15d
	cmpl 0x2C(%rbp),%r15d
	jnl L_530845
L_372948:
	movslq %r15d,%r14
	movq %r14,0x58(%rbp)
	movq 0x38(%rbp),%r15
	movq 0x0(%r15,%r14,8),%r13
	movq %r13,0x60(%rbp)
	cmpq $0x1,%r13
	jne L_530843
.p2align 0x4,,0x7
L_372957:
	incl 0x44(%rbp)
	jmp loop_3752
.p2align 0x4
L_530843:
L_372949:
	cmpq %r12,(gcState+0x8)(%rip)
	jnb L_372950
L_372958:
	movq (c_stackP+0x0)(%rip),%rsp
	movl $0x0,%r15d
	movl %r15d,%edx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x70,%rbp
	leaq (L_372959+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_collect
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_372959
.p2align 0x4
.long 0x5583
L_372959:
	addq $0xFFFFFFFFFFFFFF90,%rbp
L_372950:
	movq $0x28D1,0x0(%r12)
	movq %r12,%r15
	addq $0x8,%r15
	addq $0x18,%r12
	movq 0x60(%rbp),%r14
	movq %r14,0x0(%r15)
	movq $0x1,0x8(%r15)
	movq $0x28D1,0x0(%r12)
	movq %r12,%r14
	addq $0x8,%r14
	movq %r15,0x8(%r14)
	addq $0x18,%r12
	movq 0x50(%rbp),%r15
	movq %r15,0x0(%r14)
	movq %r14,0x68(%rbp)
	addq $0x68,%rbp
	leaq (L_372951+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	jmp concat_13
.p2align 0x4
L_530845:
L_372947:
	incl 0x28(%rbp)
	jmp loop_3751
.p2align 0x4
L_530846:
L_372962:
	movq (globalObjptr+0x4F8)(%rip),%r15
	movq %r15,(globalObjptrNonRoot+0x0)(%rip)
	movq (gcState+0x560)(%rip),%rbp
	addq (gcState+0x20)(%rip),%rbp
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530847:
L_372937:
	movq (globalObjptr+0x4D8)(%rip),%r15
	movq %r15,(globalObjptrNonRoot+0x0)(%rip)
	movq (gcState+0x560)(%rip),%rbp
	addq (gcState+0x20)(%rip),%rbp
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530849:
L_372940:
	movq (globalObjptr+0xF50)(%rip),%r14
	movq $0xF47,0xFFFFFFFFFFFFFFF8(%r14)
	movq %r14,0x0(%rbp)
	movq 0x30(%rbp),%r14
	movq %r14,0x8(%rbp)
	movq 0x38(%rbp),%r14
	movq %r14,0x10(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
.long 0x48A
L_373200:
	addq $0xFFFFFFFFFFFFFFE0,%rbp
	movslq 0x10(%rbp),%rdx
	movq %rdx,0x18(%rbp)
	testq %rdx,%rdx
	jz L_530855
L_373201:
	cmpq $0x7FFFFFFF,%rdx
	ja L_373007
L_373202:
	movq (c_stackP+0x0)(%rip),%rsp
	movq $0xAAB,%rcx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x28,%rbp
	leaq (L_373203+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_arrayAllocate
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373203
.p2align 0x4
.long 0x649
L_373203:
	addq $0xFFFFFFFFFFFFFFD8,%rbp
	movq %rax,%r15
L_373204:
	xorq %r14,%r14
.p2align 0x4,,0x7
loop_3767:
	cmpq 0x18(%rbp),%r14
	jnl L_530853
L_373206:
	movl %r14d,%r11d
	cmpl %r11d,0x8(%rbp)
	je L_530852
L_373207:
	movq $0x1,%r13
L_373208:
	movq %r15,%r11
	shrq $0x8,%r11
	movq (gcState+0x3C8)(%rip),%r10
	movb $0x1,0x0(%r10,%r11,1)
	movq %r13,0x0(%r15,%r14,8)
	incq %r14
	jmp loop_3767
.p2align 0x4
L_530852:
L_373209:
	movq (globalObjptr+0xF50)(%rip),%r13
	movq $0xF47,0xFFFFFFFFFFFFFFF8(%r13)
	jmp L_373208
.p2align 0x4
L_530853:
L_373205:
	movq $0x191D,0xFFFFFFFFFFFFFFF8(%r15)
	movq %r15,0x8(%rbp)
	movq %r15,0x10(%rbp)
	movq $0x1,0x0(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530855:
L_373211:
	movq (globalObjptr+0x1458)(%rip),%r15
	jmp L_373204
.p2align 0x4
.long 0x558E
L_373157:
	addq $0xFFFFFFFFFFFFFF90,%rbp
	movq 0x70(%rbp),%r15
	movq %r15,0x68(%rbp)
	movq 0x78(%rbp),%r15
	movq %r15,0x70(%rbp)
	movq 0x80(%rbp),%rdx
	movq %rdx,0x78(%rbp)
	movslq 0x10(%rbp),%rdx
	movq %rdx,0x80(%rbp)
	cmpq $0x0,%rdx
	sete %bl
	movzbl %bl,%ebx
	movl %ebx,0x14(%rbp)
	je L_530872
L_373158:
	cmpq $0x7FFFFFFF,%rdx
	ja L_373007
L_373159:
	movq (c_stackP+0x0)(%rip),%rsp
	movq $0xAAB,%rcx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x90,%rbp
	leaq (L_373160+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_arrayAllocate
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373160
.p2align 0x4
.long 0x5591
L_373160:
	addq $0xFFFFFFFFFFFFFF70,%rbp
	movq %rax,0x88(%rbp)
L_373161:
	xorq %r15,%r15
.p2align 0x4,,0x7
loop_3765:
	cmpq 0x80(%rbp),%r15
	jnl L_530860
L_373185:
	movl %r15d,%r13d
	movslq %r13d,%r14
	movq 0x60(%rbp),%r13
	cmpq 0xFFFFFFFFFFFFFFF0(%r13),%r14
	jnb L_372953
L_373187:
	movq 0x0(%r13,%r14,8),%r11
	movq 0x78(%rbp),%r13
	cmpq 0xFFFFFFFFFFFFFFF0(%r13),%r14
	jnb L_530858
L_373189:
	movq 0x0(%r13,%r14,8),%r10
	cmpq $0x1,%r11
	je L_530857
L_373190:
	cmpq $0x1,%r10
	jne L_530856
	movq %r11,%r14
L_373192:
	movq 0x88(%rbp),%r13
	movq %r13,%r11
	shrq $0x8,%r11
	movq (gcState+0x3C8)(%rip),%r10
	movb $0x1,0x0(%r10,%r11,1)
	movq %r14,0x0(%r13,%r15,8)
	incq %r15
	jmp loop_3765
.p2align 0x4
L_530856:
L_373082:
	movq (globalObjptr+0x1450)(%rip),%r15
	movq %r15,(globalObjptrNonRoot+0x0)(%rip)
	movq (gcState+0x560)(%rip),%rbp
	addq (gcState+0x20)(%rip),%rbp
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530857:
L_373193:
	movq %r10,%r14
	jmp L_373192
.p2align 0x4
L_530858:
L_372953:
	movq $0x6,(globalObjptrNonRoot+0x0)(%rip)
	movq (gcState+0x560)(%rip),%rbp
	addq (gcState+0x20)(%rip),%rbp
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530860:
L_373162:
	movq 0x88(%rbp),%r15
	movq $0x191D,0xFFFFFFFFFFFFFFF8(%r15)
	movl 0x14(%rbp),%r15d
	testl %r15d,%r15d
	jnz L_530870
L_373163:
	movq 0x80(%rbp),%rdx
	cmpq $0x7FFFFFFF,%rdx
	ja L_373007
L_373164:
	movq (c_stackP+0x0)(%rip),%rsp
	movq $0xAAB,%rcx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x98,%rbp
	leaq (L_373165+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_arrayAllocate
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373165
.p2align 0x4
.long 0x5596
L_373165:
	addq $0xFFFFFFFFFFFFFF68,%rbp
	movq %rax,%r15
L_373166:
	xorq %r14,%r14
.p2align 0x4,,0x7
loop_3766:
	cmpq 0x80(%rbp),%r14
	jnl L_530865
L_373174:
	movl %r14d,%r11d
	movslq %r11d,%r13
	movq 0x58(%rbp),%r11
	cmpq 0xFFFFFFFFFFFFFFF0(%r11),%r13
	jnb L_372953
L_373176:
	movq 0x0(%r11,%r13,8),%r10
	movq 0x70(%rbp),%r11
	cmpq 0xFFFFFFFFFFFFFFF0(%r11),%r13
	jnb L_372953
L_373178:
	movq 0x0(%r11,%r13,8),%r9
	cmpq $0x1,%r10
	je L_530862
L_373179:
	cmpq $0x1,%r9
	jne L_373082
	movq %r10,%r13
L_373181:
	movq %r15,%r11
	shrq $0x8,%r11
	movq (gcState+0x3C8)(%rip),%r10
	movb $0x1,0x0(%r10,%r11,1)
	movq %r13,0x0(%r15,%r14,8)
	incq %r14
	jmp loop_3766
.p2align 0x4
L_530862:
L_373182:
	movq %r9,%r13
	jmp L_373181
.p2align 0x4
L_530865:
L_373167:
	movq $0x191D,0xFFFFFFFFFFFFFFF8(%r15)
	cmpq $0x1,0x50(%rbp)
	je L_530867
L_373168:
	movq 0x48(%rbp),%r14
	cmpq $0x1,%r14
	je L_530866
L_373169:
	movq %r15,0x58(%rbp)
	movq 0x0(%r14),%r15
	movq 0x8(%r14),%r14
	movq %r14,0x48(%rbp)
	movq 0x88(%rbp),%r14
	movq %r14,0x60(%rbp)
	jmp L_373156
.p2align 0x4
L_530866:
L_373170:
	movq %r15,0x8(%rbp)
	movq 0x50(%rbp),%r15
	movq %r15,0x0(%rbp)
	movq 0x88(%rbp),%r15
	movq %r15,0x10(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530867:
L_373171:
	movq 0x48(%rbp),%r14
	cmpq $0x1,%r14
	je L_530868
L_373172:
	movq %r15,0x58(%rbp)
	movq 0x0(%r14),%r15
	movq 0x8(%r14),%r14
	movq %r14,0x48(%rbp)
	movq 0x68(%rbp),%r14
	movq %r14,0x50(%rbp)
	movq 0x88(%rbp),%r14
	movq %r14,0x60(%rbp)
	jmp L_373156
.p2align 0x4
L_530868:
L_373173:
	movq %r15,0x8(%rbp)
	movq 0x68(%rbp),%r15
	movq %r15,0x0(%rbp)
	movq 0x88(%rbp),%r15
	movq %r15,0x10(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530870:
L_373184:
	movq (globalObjptr+0x1448)(%rip),%r15
	jmp L_373166
.p2align 0x4
L_530872:
L_373195:
	movq (globalObjptr+0x1448)(%rip),%r15
	movq %r15,0x88(%rbp)
	jmp L_373161
.p2align 0x4
.long 0x558E
L_373026:
	addq $0xFFFFFFFFFFFFFF90,%rbp
	movq 0x70(%rbp),%r15
	movq %r15,0x68(%rbp)
	movq 0x78(%rbp),%r15
	movq %r15,0x70(%rbp)
	movq 0x80(%rbp),%r15
	movq %r15,0x78(%rbp)
	movq 0x58(%rbp),%r15
	movq 0xFFFFFFFFFFFFFFF0(%r15),%r14
	movl %r14d,%r13d
	movl %r13d,0x14(%rbp)
	movslq %r13d,%r11
	movq %r11,0x80(%rbp)
	cmpq %r14,%r11
	jne L_372937
L_373028:
	cmpl $0x0,%r13d
	jl L_372962
L_373029:
	movl $0x0,0x88(%rbp)
.p2align 0x4,,0x7
loop_3759:
	movl 0x88(%rbp),%r15d
	cmpl 0x14(%rbp),%r15d
	jnl L_530879
L_373131:
	movslq %r15d,%r14
	movq %r14,0x90(%rbp)
	movq 0x58(%rbp),%r15
	movq 0x0(%r15,%r14,8),%r13
	movq %r13,0x98(%rbp)
	cmpq $0x1,%r13
	je L_373137
L_373132:
	movq 0x78(%rbp),%r15
	movq 0xFFFFFFFFFFFFFFF0(%r15),%r14
	movl %r14d,%r13d
	movl %r13d,0x8C(%rbp)
	movslq %r13d,%r11
	cmpq %r14,%r11
	jne L_372937
L_373134:
	cmpl $0x0,%r13d
	jl L_372962
L_373135:
	movl $0x0,0xA0(%rbp)
loop_3764:
	movl 0xA0(%rbp),%r15d
	cmpl 0x8C(%rbp),%r15d
	jnl L_530875
L_373138:
	movslq %r15d,%r14
	movq %r14,0xA8(%rbp)
	movq 0x78(%rbp),%r15
	movq 0x0(%r15,%r14,8),%r13
	movq %r13,0xB0(%rbp)
	cmpq $0x1,%r13
	jne L_530873
.p2align 0x4,,0x7
L_373146:
	incl 0xA0(%rbp)
	jmp loop_3764
.p2align 0x4
L_530873:
L_373139:
	cmpq %r12,(gcState+0x8)(%rip)
	jnb L_373140
L_373147:
	movq (c_stackP+0x0)(%rip),%rsp
	movl $0x0,%r15d
	movl %r15d,%edx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0xC0,%rbp
	leaq (L_373148+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_collect
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373148
.p2align 0x4
.long 0x559A
L_373148:
	addq $0xFFFFFFFFFFFFFF40,%rbp
L_373140:
	movq $0x28D1,0x0(%r12)
	movq %r12,%r15
	addq $0x8,%r15
	addq $0x18,%r12
	movq 0xB0(%rbp),%r14
	movq %r14,0x0(%r15)
	movq $0x1,0x8(%r15)
	movq $0x28D1,0x0(%r12)
	movq %r12,%r14
	addq $0x8,%r14
	movq %r15,0x8(%r14)
	addq $0x18,%r12
	movq 0x98(%rbp),%r15
	movq %r15,0x0(%r14)
	movq %r14,0xB8(%rbp)
	addq $0xB8,%rbp
	leaq (L_373141+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	jmp concat_13
.p2align 0x4
L_530875:
L_373137:
	incl 0x88(%rbp)
	jmp loop_3759
.p2align 0x4
L_530879:
L_373030:
	cmpq %r12,(gcState+0x8)(%rip)
	jnb L_373031
L_373129:
	movq (c_stackP+0x0)(%rip),%rsp
	movl $0x0,%r14d
	movl %r14d,%edx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r14
	movq %r14,%rdi
	xorq %rax,%rax
	addq $0x90,%rbp
	leaq (L_373130+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_collect
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373130
.p2align 0x4
.long 0x5591
L_373130:
	addq $0xFFFFFFFFFFFFFF70,%rbp
L_373031:
	cmpq $0x1,0x50(%rbp)
	je L_530913
L_373032:
	movq 0x78(%rbp),%r15
	movq 0xFFFFFFFFFFFFFFF0(%r15),%r14
	movl %r14d,%r13d
	movslq %r13d,%rdx
	movq %rdx,0x88(%rbp)
	cmpq %r14,%rdx
	jne L_372937
L_373034:
	testq %rdx,%rdx
	jz L_530911
L_373035:
	cmpq $0x7FFFFFFF,%rdx
	ja L_373007
L_373036:
	movq (c_stackP+0x0)(%rip),%rsp
	movq $0xAAB,%rcx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x98,%rbp
	leaq (L_373037+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_arrayAllocate
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373037
.p2align 0x4
.long 0x558F
L_373037:
	addq $0xFFFFFFFFFFFFFF68,%rbp
	movq %rax,0x90(%rbp)
L_373038:
	movq $0x0,0x98(%rbp)
.p2align 0x4,,0x7
loop_3760:
	movq 0x98(%rbp),%r14
	cmpq 0x88(%rbp),%r14
	jnl L_530882
L_373116:
	movl %r14d,%r13d
	movslq %r13d,%r15
	movq 0x78(%rbp),%r14
	movq 0x0(%r14,%r15,8),%r13
	movq %r13,0xA0(%rbp)
	cmpq $0x1,%r13
	jne L_530880
L_373123:
	movq $0x1,%r15
.p2align 0x4,,0x7
L_373120:
	movq 0x90(%rbp),%r14
	movq %r14,%r13
	shrq $0x8,%r13
	movq (gcState+0x3C8)(%rip),%r11
	movb $0x1,0x0(%r11,%r13,1)
	movq 0x98(%rbp),%r13
	movq %r15,0x0(%r14,%r13,8)
	incq %r13
	movq %r13,0x98(%rbp)
	jmp loop_3760
.p2align 0x4
L_530880:
L_373117:
	cmpq %r12,(gcState+0x8)(%rip)
	jnb L_373118
L_373121:
	movq (c_stackP+0x0)(%rip),%rsp
	movl $0x0,%r15d
	movl %r15d,%edx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0xB0,%rbp
	leaq (L_373122+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_collect
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373122
.p2align 0x4
.long 0x5598
L_373122:
	addq $0xFFFFFFFFFFFFFF50,%rbp
L_373118:
	movq $0x28D1,0x0(%r12)
	movq %r12,%r15
	addq $0x8,%r15
	addq $0x18,%r12
	movq 0xA0(%rbp),%r14
	movq %r14,0x0(%r15)
	movq $0x1,0x8(%r15)
	movq $0x28D1,0x0(%r12)
	movq %r12,%r14
	addq $0x8,%r14
	movq %r15,0x8(%r14)
	addq $0x18,%r12
	movq 0x50(%rbp),%r15
	movq %r15,0x0(%r14)
	movq %r14,0xA8(%rbp)
	addq $0xA8,%rbp
	leaq (L_373119+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	jmp concat_13
.p2align 0x4
L_530882:
L_373039:
	movq 0x90(%rbp),%r15
	movq $0x191D,0xFFFFFFFFFFFFFFF8(%r15)
	movslq 0x10(%rbp),%rdx
	movq %rdx,0x78(%rbp)
	testq %rdx,%rdx
	jz L_530909
L_373040:
	cmpq $0x7FFFFFFF,%rdx
	ja L_373007
L_373041:
	movq (c_stackP+0x0)(%rip),%rsp
	movq $0xAAB,%rcx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0xA0,%rbp
	leaq (L_373042+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_arrayAllocate
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373042
.p2align 0x4
.long 0x5590
L_373042:
	addq $0xFFFFFFFFFFFFFF60,%rbp
	movq %rax,0x88(%rbp)
L_373043:
	xorq %r15,%r15
.p2align 0x4,,0x7
loop_3761:
	cmpq 0x78(%rbp),%r15
	jnl L_530887
L_373105:
	movl %r15d,%r13d
	movslq %r13d,%r14
	movq 0x60(%rbp),%r13
	cmpq 0xFFFFFFFFFFFFFFF0(%r13),%r14
	jnb L_372953
L_373107:
	movq 0x0(%r13,%r14,8),%r11
	movq 0x90(%rbp),%r13
	cmpq 0xFFFFFFFFFFFFFFF0(%r13),%r14
	jnb L_372953
L_373109:
	movq 0x0(%r13,%r14,8),%r10
	cmpq $0x1,%r11
	je L_530884
L_373110:
	cmpq $0x1,%r10
	jne L_373082
	movq %r11,%r14
L_373112:
	movq 0x88(%rbp),%r13
	movq %r13,%r11
	shrq $0x8,%r11
	movq (gcState+0x3C8)(%rip),%r10
	movb $0x1,0x0(%r10,%r11,1)
	movq %r14,0x0(%r13,%r15,8)
	incq %r15
	jmp loop_3761
.p2align 0x4
L_530884:
L_373113:
	movq %r10,%r14
	jmp L_373112
.p2align 0x4
L_530887:
L_373044:
	cmpq %r12,(gcState+0x8)(%rip)
	jnb L_373045
L_373103:
	movq (c_stackP+0x0)(%rip),%rsp
	movl $0x0,%r15d
	movl %r15d,%edx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x98,%rbp
	leaq (L_373104+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_collect
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373104
.p2align 0x4
.long 0x5596
L_373104:
	addq $0xFFFFFFFFFFFFFF68,%rbp
L_373045:
	movq 0x88(%rbp),%r15
	movq $0x191D,0xFFFFFFFFFFFFFFF8(%r15)
	movq 0x68(%rbp),%r14
	cmpq $0x1,%r14
	je L_530905
L_373046:
	movq %r14,0x60(%rbp)
	movq %r15,0x78(%rbp)
L_373047:
	movq 0x80(%rbp),%rdx
	testq %rdx,%rdx
	jz L_530904
L_373048:
	cmpq $0x7FFFFFFF,%rdx
	ja L_373007
L_373049:
	movq (c_stackP+0x0)(%rip),%rsp
	movq $0xAAB,%rcx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x90,%rbp
	leaq (L_373050+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_arrayAllocate
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373050
.p2align 0x4
.long 0x5591
L_373050:
	addq $0xFFFFFFFFFFFFFF70,%rbp
	movq %rax,0x88(%rbp)
L_373051:
	movq $0x0,0x90(%rbp)
.p2align 0x4,,0x7
loop_3762:
	movq 0x90(%rbp),%r14
	cmpq 0x80(%rbp),%r14
	jnl L_530890
L_373088:
	movl %r14d,%r13d
	movslq %r13d,%r15
	movq 0x58(%rbp),%r14
	movq 0x0(%r14,%r15,8),%r13
	movq %r13,0x98(%rbp)
	cmpq $0x1,%r13
	jne L_530888
L_373095:
	movq $0x1,%r15
.p2align 0x4,,0x7
L_373092:
	movq 0x88(%rbp),%r14
	movq %r14,%r13
	shrq $0x8,%r13
	movq (gcState+0x3C8)(%rip),%r11
	movb $0x1,0x0(%r11,%r13,1)
	movq 0x90(%rbp),%r13
	movq %r15,0x0(%r14,%r13,8)
	incq %r13
	movq %r13,0x90(%rbp)
	jmp loop_3762
.p2align 0x4
L_530888:
L_373089:
	cmpq %r12,(gcState+0x8)(%rip)
	jnb L_373090
L_373093:
	movq (c_stackP+0x0)(%rip),%rsp
	movl $0x0,%r15d
	movl %r15d,%edx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0xA8,%rbp
	leaq (L_373094+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_collect
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373094
.p2align 0x4
.long 0x5595
L_373094:
	addq $0xFFFFFFFFFFFFFF58,%rbp
L_373090:
	movq $0x28D1,0x0(%r12)
	movq %r12,%r15
	addq $0x8,%r15
	addq $0x18,%r12
	movq 0x98(%rbp),%r14
	movq %r14,0x0(%r15)
	movq $0x1,0x8(%r15)
	movq $0x28D1,0x0(%r12)
	movq %r12,%r14
	addq $0x8,%r14
	movq %r15,0x8(%r14)
	addq $0x18,%r12
	movq 0x60(%rbp),%r15
	movq %r15,0x0(%r14)
	movq %r14,0xA0(%rbp)
	addq $0xA0,%rbp
	leaq (L_373091+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	jmp concat_13
.p2align 0x4
L_530890:
L_373052:
	movq 0x88(%rbp),%r15
	movq $0x191D,0xFFFFFFFFFFFFFFF8(%r15)
	movslq 0x10(%rbp),%rdx
	movq %rdx,0x58(%rbp)
	testq %rdx,%rdx
	jz L_530902
L_373053:
	cmpq $0x7FFFFFFF,%rdx
	ja L_373007
L_373054:
	movq (c_stackP+0x0)(%rip),%rsp
	movq $0xAAB,%rcx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x98,%rbp
	leaq (L_373055+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_arrayAllocate
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373055
.p2align 0x4
.long 0x5592
L_373055:
	addq $0xFFFFFFFFFFFFFF68,%rbp
	movq %rax,0x60(%rbp)
L_373056:
	xorq %r15,%r15
.p2align 0x4,,0x7
loop_3763:
	cmpq 0x58(%rbp),%r15
	jnl L_530895
L_373076:
	movl %r15d,%r13d
	movslq %r13d,%r14
	movq 0x70(%rbp),%r13
	cmpq 0xFFFFFFFFFFFFFFF0(%r13),%r14
	jnb L_372953
L_373078:
	movq 0x0(%r13,%r14,8),%r11
	movq 0x88(%rbp),%r13
	cmpq 0xFFFFFFFFFFFFFFF0(%r13),%r14
	jnb L_372953
L_373080:
	movq 0x0(%r13,%r14,8),%r10
	cmpq $0x1,%r11
	je L_530892
L_373081:
	cmpq $0x1,%r10
	jne L_373082
	movq %r11,%r14
L_373084:
	movq 0x60(%rbp),%r13
	movq %r13,%r11
	shrq $0x8,%r11
	movq (gcState+0x3C8)(%rip),%r10
	movb $0x1,0x0(%r10,%r11,1)
	movq %r14,0x0(%r13,%r15,8)
	incq %r15
	jmp loop_3763
.p2align 0x4
L_530892:
L_373085:
	movq %r10,%r14
	jmp L_373084
.p2align 0x4
L_530895:
L_373057:
	cmpq %r12,(gcState+0x8)(%rip)
	jnb L_373058
L_373074:
	movq (c_stackP+0x0)(%rip),%rsp
	movl $0x0,%r15d
	movl %r15d,%edx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x88,%rbp
	leaq (L_373075+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_collect
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373075
.p2align 0x4
.long 0x5593
L_373075:
	addq $0xFFFFFFFFFFFFFF78,%rbp
L_373058:
	movq 0x60(%rbp),%r14
	movq $0x191D,0xFFFFFFFFFFFFFFF8(%r14)
L_373059:
	movq 0x50(%rbp),%r15
	andq $0x3,%r15
	jz L_530897
L_373060:
	movq 0x78(%rbp),%r15
L_373061:
	movq 0x48(%rbp),%r13
	cmpq $0x1,%r13
	je L_530896
L_373062:
	movq %r14,0x58(%rbp)
	movq %r15,0x60(%rbp)
	movq 0x0(%r13),%r15
	movq 0x8(%r13),%r13
	movq %r13,0x48(%rbp)
	movq $0x1,0x50(%rbp)
	jmp L_373025
.p2align 0x4
L_530896:
L_373063:
	movq %r14,0x8(%rbp)
	movq %r15,0x10(%rbp)
	movq $0x1,0x0(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530897:
L_373064:
	movq 0x50(%rbp),%r15
	movq 0x78(%rbp),%r13
	movq %r13,0x50(%rbp)
	movq %r14,0x58(%rbp)
L_373066:
	movq 0x68(%rbp),%r14
	movq %r14,%r13
	andq $0x3,%r13
	jnz L_530898
L_373070:
	movq $0x28D1,0x0(%r12)
	movq %r12,%r13
	addq $0x8,%r13
	addq $0x18,%r12
	movq %r14,0x0(%r13)
	movq $0x1,0x8(%r13)
	movq $0x28D1,0x0(%r12)
	movq %r12,%r14
	addq $0x8,%r14
	movq %r15,0x0(%r14)
	movq %r13,0x8(%r14)
	movq %r14,0x68(%rbp)
	addq $0x18,%r12
	addq $0x68,%rbp
	leaq (L_373071+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	jmp concat_13
.p2align 0x4
L_530898:
L_373067:
	movq 0x48(%rbp),%r13
	cmpq $0x1,%r13
	je L_530899
L_373068:
	movq 0x0(%r13),%r15
	movq 0x8(%r13),%r13
	movq %r13,0x48(%rbp)
	movq 0x50(%rbp),%r13
	movq %r13,0x60(%rbp)
	movq $0x1,0x50(%rbp)
	jmp L_373025
.p2align 0x4
L_530899:
L_373069:
	movq $0x1,0x0(%rbp)
	movq 0x58(%rbp),%r15
	movq %r15,0x8(%rbp)
	movq 0x50(%rbp),%r15
	movq %r15,0x10(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530902:
L_373087:
	movq (globalObjptr+0x1448)(%rip),%r15
	movq %r15,0x60(%rbp)
	jmp L_373056
.p2align 0x4
L_530904:
L_373097:
	movq (globalObjptr+0x1440)(%rip),%r15
	movq %r15,0x88(%rbp)
	jmp L_373051
.p2align 0x4
L_530905:
L_373098:
L_373100:
	movq 0x50(%rbp),%r14
	andq $0x3,%r14
	jz L_530906
L_373101:
	movq 0x70(%rbp),%r14
	jmp L_373061
.p2align 0x4
L_530906:
L_373102:
	movq 0x70(%rbp),%r14
	movq %r14,0x58(%rbp)
	movq 0x50(%rbp),%r14
	movq %r15,0x50(%rbp)
	movq %r14,%r15
	jmp L_373066
.p2align 0x4
L_530909:
L_373115:
	movq (globalObjptr+0x1448)(%rip),%r15
	movq %r15,0x88(%rbp)
	jmp L_373043
.p2align 0x4
L_530911:
L_373125:
	movq (globalObjptr+0x1440)(%rip),%r15
	movq %r15,0x90(%rbp)
	jmp L_373038
.p2align 0x4
L_530913:
L_373126:
	movq 0x68(%rbp),%r15
	cmpq $0x1,%r15
	je L_530914
L_373127:
	movq 0x60(%rbp),%r14
	movq %r14,0x78(%rbp)
	movq %r15,0x60(%rbp)
	jmp L_373047
.p2align 0x4
L_530914:
L_373128:
	movq 0x60(%rbp),%r14
	xchgq %r14,%r15
	jmp L_373100
.p2align 0x4
.long 0x90C
L_372966:
	addq $0xFFFFFFFFFFFFFFA8,%rbp
	movq 0x58(%rbp),%r15
	movq %r15,0x50(%rbp)
	movq 0x60(%rbp),%r15
	movq %r15,0x58(%rbp)
	movq 0x68(%rbp),%r15
	movq %r15,0x60(%rbp)
	cmpq %r12,(gcState+0x8)(%rip)
	jnb L_372967
L_373021:
	movq (c_stackP+0x0)(%rip),%rsp
	movl $0x0,%r15d
	movl %r15d,%edx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x70,%rbp
	leaq (L_373022+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_collect
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373022
.p2align 0x4
.long 0x77F
L_373022:
	addq $0xFFFFFFFFFFFFFF90,%rbp
L_372967:
	movq $0x1B8B,0x0(%r12)
	movq %r12,%r15
	addq $0x8,%r15
	addq $0x10,%r12
	movq 0x48(%rbp),%r14
	movq %r14,0x0(%r15)
	movq %r15,0x68(%rbp)
	movq $0x1B8D,0x0(%r12)
	movq %r12,%r15
	addq $0x8,%r15
	addq $0x10,%r12
	movq %r12,(gcState+0x0)(%rip)
	movq %r14,0x0(%r15)
	movq %r15,0x70(%rbp)
	movq (c_stackP+0x0)(%rip),%rsp
	movq $0x1439,%rcx
	movq $0x1,%rdx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x80,%rbp
	leaq (L_372968+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	call GC_arrayAllocate
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_372968
.p2align 0x4
.long 0x16E2
L_372968:
	addq $0xFFFFFFFFFFFFFF80,%rbp
	movq %rax,0x78(%rbp)
	xorq %r15,%r15
.p2align 0x4,,0x7
loop_3753:
	cmpq $0x1,%r15
	jnl L_530918
L_373020:
	movq 0x78(%rbp),%r14
	movq %r14,%r13
	shrq $0x8,%r13
	movq (gcState+0x3C8)(%rip),%r11
	movb $0x1,0x0(%r11,%r13,1)
	movq 0x68(%rbp),%r13
	movq %r13,0x0(%r14,%r15,8)
	incq %r15
	jmp loop_3753
.p2align 0x4
L_530918:
L_372969:
	movq 0x78(%rbp),%r15
	movq $0xF47,0xFFFFFFFFFFFFFFF8(%r15)
	movq 0x60(%rbp),%r15
	movq 0xFFFFFFFFFFFFFFF0(%r15),%r14
	movl %r14d,%r13d
	movslq %r13d,%rdx
	movq %rdx,0x80(%rbp)
	cmpq %r14,%rdx
	jne L_372937
L_372971:
	testq %rdx,%rdx
	jz L_530934
L_372972:
	cmpq $0x7FFFFFFF,%rdx
	ja L_373007
L_372973:
	movq (c_stackP+0x0)(%rip),%rsp
	movq $0xAAB,%rcx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x90,%rbp
	leaq (L_372974+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_arrayAllocate
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_372974
.p2align 0x4
.long 0x5584
L_372974:
	addq $0xFFFFFFFFFFFFFF70,%rbp
	movq %rax,0x88(%rbp)
L_372975:
	movq $0x0,0x90(%rbp)
.p2align 0x4,,0x7
loop_3754:
	movq 0x90(%rbp),%r14
	cmpq 0x80(%rbp),%r14
	jnl L_530921
L_373010:
	movl %r14d,%r13d
	movslq %r13d,%r15
	movq 0x60(%rbp),%r14
	movq 0x0(%r14,%r15,8),%r13
	movq %r13,0x98(%rbp)
	cmpq $0x1,%r13
	jne L_530919
L_373017:
	movq $0x1,%r15
.p2align 0x4,,0x7
L_373014:
	movq 0x88(%rbp),%r14
	movq %r14,%r13
	shrq $0x8,%r13
	movq (gcState+0x3C8)(%rip),%r11
	movb $0x1,0x0(%r11,%r13,1)
	movq 0x90(%rbp),%r13
	movq %r15,0x0(%r14,%r13,8)
	incq %r13
	movq %r13,0x90(%rbp)
	jmp loop_3754
.p2align 0x4
L_530919:
L_373011:
	cmpq %r12,(gcState+0x8)(%rip)
	jnb L_373012
L_373015:
	movq (c_stackP+0x0)(%rip),%rsp
	movl $0x0,%r15d
	movl %r15d,%edx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0xA8,%rbp
	leaq (L_373016+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_collect
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373016
.p2align 0x4
.long 0x558D
L_373016:
	addq $0xFFFFFFFFFFFFFF58,%rbp
L_373012:
	movq $0x28D1,0x0(%r12)
	movq %r12,%r15
	addq $0x8,%r15
	addq $0x18,%r12
	movq 0x98(%rbp),%r14
	movq %r14,0x0(%r15)
	movq $0x1,0x8(%r15)
	movq $0x28D1,0x0(%r12)
	movq %r12,%r14
	addq $0x8,%r14
	movq %r15,0x8(%r14)
	addq $0x18,%r12
	movq 0x78(%rbp),%r15
	movq %r15,0x0(%r14)
	movq %r14,0xA0(%rbp)
	addq $0xA0,%rbp
	leaq (L_373013+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	jmp concat_13
.p2align 0x4
L_530921:
L_372976:
	movq 0x88(%rbp),%r15
	movq $0x191D,0xFFFFFFFFFFFFFFF8(%r15)
	movq (c_stackP+0x0)(%rip),%rsp
	movq $0x1439,%rcx
	movq $0x1,%rdx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x98,%rbp
	leaq (L_372977+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_arrayAllocate
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_372977
.p2align 0x4
.long 0x5585
L_372977:
	addq $0xFFFFFFFFFFFFFF68,%rbp
	movq %rax,0x60(%rbp)
	xorq %r15,%r15
.p2align 0x4,,0x7
loop_3755:
	cmpq $0x1,%r15
	jnl L_530922
L_373009:
	movq 0x60(%rbp),%r14
	movq %r14,%r13
	shrq $0x8,%r13
	movq (gcState+0x3C8)(%rip),%r11
	movb $0x1,0x0(%r11,%r13,1)
	movq 0x70(%rbp),%r13
	movq %r13,0x0(%r14,%r15,8)
	incq %r15
	jmp loop_3755
.p2align 0x4
L_530922:
L_372978:
	movq 0x60(%rbp),%r15
	movq $0xF47,0xFFFFFFFFFFFFFFF8(%r15)
	movq 0x58(%rbp),%r15
	movq 0xFFFFFFFFFFFFFFF0(%r15),%r14
	movl %r14d,%r13d
	movslq %r13d,%rdx
	movq %rdx,0x78(%rbp)
	cmpq %rdx,%r14
	jne L_372937
L_372980:
	testq %rdx,%rdx
	jz L_530931
L_372981:
	cmpq $0x7FFFFFFF,%rdx
	ja L_373007
L_372982:
	movq (c_stackP+0x0)(%rip),%rsp
	movq $0xAAB,%rcx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x98,%rbp
	leaq (L_372983+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_arrayAllocate
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_372983
.p2align 0x4
.long 0x5586
L_372983:
	addq $0xFFFFFFFFFFFFFF68,%rbp
	movq %rax,0x80(%rbp)
L_372984:
	movq $0x0,0x90(%rbp)
.p2align 0x4,,0x7
loop_3756:
	movq 0x90(%rbp),%r14
	cmpq 0x78(%rbp),%r14
	jnl L_530925
L_372998:
	movl %r14d,%r13d
	movslq %r13d,%r15
	movq 0x58(%rbp),%r14
	movq 0x0(%r14,%r15,8),%r13
	movq %r13,0x98(%rbp)
	cmpq $0x1,%r13
	jne L_530923
L_373005:
	movq $0x1,%r15
.p2align 0x4,,0x7
L_373002:
	movq 0x80(%rbp),%r14
	movq %r14,%r13
	shrq $0x8,%r13
	movq (gcState+0x3C8)(%rip),%r11
	movb $0x1,0x0(%r11,%r13,1)
	movq 0x90(%rbp),%r13
	movq %r15,0x0(%r14,%r13,8)
	incq %r13
	movq %r13,0x90(%rbp)
	jmp loop_3756
.p2align 0x4
L_530923:
L_372999:
	cmpq %r12,(gcState+0x8)(%rip)
	jnb L_373000
L_373003:
	movq (c_stackP+0x0)(%rip),%rsp
	movl $0x0,%r15d
	movl %r15d,%edx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0xA8,%rbp
	leaq (L_373004+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_collect
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373004
.p2align 0x4
.long 0x558B
L_373004:
	addq $0xFFFFFFFFFFFFFF58,%rbp
L_373000:
	movq $0x28D1,0x0(%r12)
	movq %r12,%r15
	addq $0x8,%r15
	addq $0x18,%r12
	movq 0x98(%rbp),%r14
	movq %r14,0x0(%r15)
	movq $0x1,0x8(%r15)
	movq $0x28D1,0x0(%r12)
	movq %r12,%r14
	addq $0x8,%r14
	movq %r15,0x8(%r14)
	addq $0x18,%r12
	movq 0x60(%rbp),%r15
	movq %r15,0x0(%r14)
	movq %r14,0xA0(%rbp)
	addq $0xA0,%rbp
	leaq (L_373001+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	jmp concat_13
.p2align 0x4
L_530925:
L_372985:
	movq 0x80(%rbp),%r15
	movq $0x191D,0xFFFFFFFFFFFFFFF8(%r15)
	cmpq $0x1,0x50(%rbp)
	je L_530929
L_372986:
	movq (c_stackP+0x0)(%rip),%rsp
	movq $0x1439,%rcx
	movq $0x1,%rdx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x98,%rbp
	leaq (L_372987+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_arrayAllocate
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_372987
.p2align 0x4
.long 0x5587
L_372987:
	addq $0xFFFFFFFFFFFFFF68,%rbp
	movq %rax,0x58(%rbp)
	xorq %r15,%r15
.p2align 0x4,,0x7
loop_3757:
	cmpq $0x1,%r15
	jnl L_530926
L_372996:
	movq 0x58(%rbp),%r14
	movq %r14,%r13
	shrq $0x8,%r13
	movq (gcState+0x3C8)(%rip),%r11
	movb $0x1,0x0(%r11,%r13,1)
	movq 0x68(%rbp),%r13
	movq %r13,0x0(%r14,%r15,8)
	incq %r15
	jmp loop_3757
.p2align 0x4
L_530926:
L_372988:
	movq 0x58(%rbp),%r15
	movq $0xF47,0xFFFFFFFFFFFFFFF8(%r15)
	movq (c_stackP+0x0)(%rip),%rsp
	movq $0x1439,%rcx
	movq $0x1,%rdx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x98,%rbp
	leaq (L_372989+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_arrayAllocate
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_372989
.p2align 0x4
.long 0x5588
L_372989:
	addq $0xFFFFFFFFFFFFFF68,%rbp
	movq %rax,0x60(%rbp)
	xorq %r15,%r15
.p2align 0x4,,0x7
loop_3758:
	cmpq $0x1,%r15
	jnl L_530927
L_372995:
	movq 0x60(%rbp),%r14
	movq %r14,%r13
	shrq $0x8,%r13
	movq (gcState+0x3C8)(%rip),%r11
	movb $0x1,0x0(%r11,%r13,1)
	movq 0x70(%rbp),%r13
	movq %r13,0x0(%r14,%r15,8)
	incq %r15
	jmp loop_3758
.p2align 0x4
L_530927:
L_372990:
	cmpq %r12,(gcState+0x8)(%rip)
	jnb L_372991
L_372993:
	movq (c_stackP+0x0)(%rip),%rsp
	movl $0x0,%r15d
	movl %r15d,%edx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x98,%rbp
	leaq (L_372994+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_collect
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_372994
.p2align 0x4
.long 0x5589
L_372994:
	addq $0xFFFFFFFFFFFFFF68,%rbp
L_372991:
	movq 0x60(%rbp),%r15
	movq $0xF47,0xFFFFFFFFFFFFFFF8(%r15)
	movq $0x28D1,0x0(%r12)
	movq %r12,%r14
	addq $0x8,%r14
	addq $0x18,%r12
	movq %r15,0x0(%r14)
	movq $0x1,0x8(%r14)
	movq $0x28D1,0x0(%r12)
	movq %r12,%r15
	addq $0x8,%r15
	movq %r14,0x8(%r15)
	addq $0x18,%r12
	movq 0x50(%rbp),%r14
	movq %r14,0x0(%r15)
	movq $0x28D1,0x0(%r12)
	movq %r12,%r14
	addq $0x8,%r14
	movq %r15,0x8(%r14)
	addq $0x18,%r12
	movq 0x58(%rbp),%r15
	movq %r15,0x0(%r14)
	movq %r14,0x98(%rbp)
	addq $0x98,%rbp
	leaq (L_372992+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	jmp concat_13
.p2align 0x4
L_530929:
L_372997:
	movq $0x1,0x0(%rbp)
	movq 0x80(%rbp),%r15
	movq %r15,0x8(%rbp)
	movq 0x88(%rbp),%r15
	movq %r15,0x10(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530931:
L_373008:
	movq (globalObjptr+0x1440)(%rip),%r15
	movq %r15,0x80(%rbp)
	jmp L_372984
.p2align 0x4
L_530934:
L_373019:
	movq (globalObjptr+0x1440)(%rip),%r15
	movq %r15,0x88(%rbp)
	jmp L_372975
.p2align 0x4
.long 0x5582
L_372951:
	addq $0xFFFFFFFFFFFFFF98,%rbp
	movq 0x68(%rbp),%r15
	movq %r15,0x60(%rbp)
	movq 0x20(%rbp),%r14
	movq 0x10(%r14),%r13
	movq 0x8(%r14),%r11
	movq 0x48(%rbp),%r10
	cmpq 0x0(%r14),%r10
	jnb L_372953
L_372954:
	movq 0x58(%rbp),%r14
	cmpq %r11,%r14
	jnb L_372953
L_372956:
	imulq %r10,%r11
	addq %r14,%r11
	movq %r13,%r14
	shrq $0x8,%r14
	movq (gcState+0x3C8)(%rip),%r10
	movb $0x1,0x0(%r10,%r14,1)
	movq %r15,0x0(%r13,%r11,8)
	jmp L_372957
.p2align 0x4
.long 0x5599
L_373141:
	addq $0xFFFFFFFFFFFFFF48,%rbp
	movq 0xB8(%rbp),%r15
	movq %r15,0xB0(%rbp)
	movq 0x20(%rbp),%r14
	movq 0x10(%r14),%r13
	movq 0x8(%r14),%r11
	movq 0x90(%rbp),%r10
	cmpq 0x0(%r14),%r10
	jnb L_372953
L_373143:
	movq 0xA8(%rbp),%r14
	cmpq %r11,%r14
	jnb L_372953
L_373145:
	imulq %r10,%r11
	addq %r14,%r11
	movq %r13,%r14
	shrq $0x8,%r14
	movq (gcState+0x3C8)(%rip),%r10
	movb $0x1,0x0(%r10,%r14,1)
	movq %r15,0x0(%r13,%r11,8)
	jmp L_373146
.p2align 0x4
.long 0x5597
L_373119:
	addq $0xFFFFFFFFFFFFFF58,%rbp
	movq 0xA8(%rbp),%r15
	movq %r15,0xA0(%rbp)
	jmp L_373120
.p2align 0x4
.long 0x5594
L_373091:
	addq $0xFFFFFFFFFFFFFF60,%rbp
	movq 0xA0(%rbp),%r15
	movq %r15,0x98(%rbp)
	jmp L_373092
.p2align 0x4
.long 0xA33
L_373071:
	addq $0xFFFFFFFFFFFFFF98,%rbp
	movq 0x68(%rbp),%r15
	movq %r15,0x60(%rbp)
	movq 0x48(%rbp),%r14
	cmpq $0x1,%r14
	je L_530941
L_373072:
	movq 0x0(%r14),%r13
	movq 0x8(%r14),%r14
	movq %r14,0x48(%rbp)
	movq 0x50(%rbp),%r14
	movq %r15,0x50(%rbp)
	movq %r14,0x60(%rbp)
	movq %r13,%r15
	jmp L_373025
.p2align 0x4
L_530941:
L_373073:
	movq %r15,0x0(%rbp)
	movq 0x58(%rbp),%r15
	movq %r15,0x8(%rbp)
	movq 0x50(%rbp),%r15
	movq %r15,0x10(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
.long 0x558C
L_373013:
	addq $0xFFFFFFFFFFFFFF60,%rbp
	movq 0xA0(%rbp),%r15
	movq %r15,0x98(%rbp)
	jmp L_373014
.p2align 0x4
.long 0x558A
L_373001:
	addq $0xFFFFFFFFFFFFFF60,%rbp
	movq 0xA0(%rbp),%r15
	movq %r15,0x98(%rbp)
	jmp L_373002
.p2align 0x4
.long 0xE2F
L_372992:
	addq $0xFFFFFFFFFFFFFF68,%rbp
	movq 0x98(%rbp),%r15
	movq %r15,0x90(%rbp)
	movq %r15,0x0(%rbp)
	movq 0x80(%rbp),%r15
	movq %r15,0x8(%rbp)
	movq 0x88(%rbp),%r15
	movq %r15,0x10(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.text
.p2align 0x4
.globl concat_13
.hidden concat_13
concat_13:
L_373228:
	cmpq %rbp,(gcState+0x18)(%rip)
	jnb L_373229
L_373272:
	movq (c_stackP+0x0)(%rip),%rsp
	movl $0x0,%r15d
	movl %r15d,%edx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x10,%rbp
	leaq (L_373273+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_collect
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373273
.p2align 0x4
.long 0x451
L_373273:
	addq $0xFFFFFFFFFFFFFFF0,%rbp
L_373229:
	movq 0x0(%rbp),%r15
	cmpq $0x1,%r15
	je L_530957
L_373230:
	movq 0x0(%r15),%r14
	movq 0x8(%r15),%r15
	movq %r15,0x0(%rbp)
	movq %r14,0x8(%rbp)
	movq $0x1,0x10(%rbp)
.p2align 0x4,,0x7
L_373231:
	cmpq %r12,(gcState+0x8)(%rip)
	jb L_530956
.p2align 0x4,,0x7
L_373232:
	movq 0x8(%rbp),%r15
	movq 0xFFFFFFFFFFFFFFF0(%r15),%r14
	movq $0xF49,0x0(%r12)
	movq %r12,%r13
	addq $0x8,%r13
	movq %r14,0x0(%r13)
	addq $0x18,%r12
	movq %r15,0x8(%r13)
	movq $0x2993,0x0(%r12)
	movq %r12,%r15
	addq $0x8,%r15
	addq $0x18,%r12
	movq %r13,0x0(%r15)
	movq 0x10(%rbp),%r14
	movq %r14,0x8(%r15)
	movq 0x0(%rbp),%r14
	cmpq $0x1,%r14
	je L_530942
L_373233:
	movq %r15,0x10(%rbp)
	movq 0x0(%r14),%r15
	movq 0x8(%r14),%r14
	movq %r14,0x0(%rbp)
	movq %r15,0x8(%rbp)
	jmp L_373231
.p2align 0x4
L_530942:
L_373234:
	movq %r13,0x8(%rbp)
	movq 0x10(%rbp),%r15
	movq %r15,0x0(%rbp)
	movq $0x1,0x10(%rbp)
.p2align 0x4,,0x7
L_373235:
	cmpq %r12,(gcState+0x8)(%rip)
	jb L_530955
.p2align 0x4,,0x7
L_373236:
	movq $0x2993,0x0(%r12)
	movq %r12,%r15
	addq $0x8,%r15
	addq $0x18,%r12
	movq 0x8(%rbp),%r14
	movq %r14,0x0(%r15)
	movq 0x10(%rbp),%r14
	movq %r14,0x8(%r15)
	movq 0x0(%rbp),%r14
	cmpq $0x1,%r14
	je L_530943
L_373237:
	movq %r15,0x10(%rbp)
	movq 0x0(%r14),%r15
	movq 0x8(%r14),%r14
	movq %r14,0x0(%rbp)
	movq %r15,0x8(%rbp)
	jmp L_373235
.p2align 0x4
L_530943:
L_373238:
	movq 0x10(%rbp),%r13
	cmpq $0x1,%r13
	je L_530950
L_373239:
	movq 0x8(%rbp),%r11
	xorq %r15,%r15
	xchgq %r11,%r14
.p2align 0x4,,0x7
L_373240:
	addq 0x0(%r14),%r15
	movq %r15,0x18(%rbp)
	cmpq $0x1,%r13
	je L_530944
L_373241:
	movq 0x0(%r13),%r14
	movq 0x8(%r13),%r13
	jmp L_373240
.p2align 0x4
L_530944:
L_373242:
	testq %r15,%r15
	jz L_530949
L_373243:
	cmpq $0x7FFFFFFF,%r15
	ja L_530948
L_373244:
	movq (c_stackP+0x0)(%rip),%rsp
	movq $0x1439,%rcx
	movq %r15,%rdx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x28,%rbp
	leaq (L_373245+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_arrayAllocate
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373245
.p2align 0x4
.long 0x49B
L_373245:
	addq $0xFFFFFFFFFFFFFFD8,%rbp
	movq %rax,%r15
L_373246:
	movq 0x10(%rbp),%r10
	movq 0x8(%rbp),%r11
	xorq %r13,%r13
	xorq %r14,%r14
.p2align 0x4,,0x7
loop_3769:
	cmpq 0x18(%rbp),%r14
	jnl L_530947
.p2align 0x4,,0x7
loop_3770:
	cmpq 0x0(%r11),%r13
	jl L_530946
L_373249:
	cmpq $0x1,%r10
	je L_530945
L_373250:
	movq 0x0(%r10),%r9
	movq 0x8(%r10),%r10
	xorq %r13,%r13
	movq %r9,%r11
	jmp loop_3770
.p2align 0x4
L_530945:
L_373251:
	movq (globalObjptr+0x5B8)(%rip),%r15
	movq %r15,(globalObjptrNonRoot+0x0)(%rip)
	movq (gcState+0x560)(%rip),%rbp
	addq (gcState+0x20)(%rip),%rbp
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530946:
L_373252:
	movq 0x8(%r11),%r9
	movq 0x0(%r9,%r13,8),%r8
	incq %r13
	movq %r15,%r9
	shrq $0x8,%r9
	movq (gcState+0x3C8)(%rip),%rsp
	movb $0x1,0x0(%rsp,%r9,1)
	movq %r8,0x0(%r15,%r14,8)
	incq %r14
	jmp loop_3769
.p2align 0x4
L_530947:
L_373247:
	movq $0xF47,0xFFFFFFFFFFFFFFF8(%r15)
	movq %r15,0x0(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530948:
L_373254:
	movq $0x5,(globalObjptrNonRoot+0x0)(%rip)
	movq (gcState+0x560)(%rip),%rbp
	addq (gcState+0x20)(%rip),%rbp
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530949:
L_373255:
	movq (globalObjptr+0x630)(%rip),%r14
	xchgq %r14,%r15
	jmp L_373246
.p2align 0x4
L_530950:
L_373256:
	movq 0x8(%rbp),%r15
	movq 0x8(%r15),%r13
	movq 0x0(%r15),%rdx
	movq %rdx,0x18(%rbp)
	cmpq 0xFFFFFFFFFFFFFFF0(%r13),%rdx
	movq %r13,0x10(%rbp)
	je L_530954
L_373257:
	testq %rdx,%rdx
	jz L_530953
L_373258:
	cmpq $0x7FFFFFFF,%rdx
	ja L_373254
L_373259:
	movq (c_stackP+0x0)(%rip),%rsp
	movq $0x1439,%rcx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x28,%rbp
	leaq (L_373260+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_arrayAllocate
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373260
.p2align 0x4
.long 0x4A4
L_373260:
	addq $0xFFFFFFFFFFFFFFD8,%rbp
	movq %rax,%r15
L_373261:
	xorq %r14,%r14
.p2align 0x4,,0x7
loop_3771:
	cmpq 0x18(%rbp),%r14
	jnl L_530951
L_373263:
	movq 0x10(%rbp),%r13
	movq 0x0(%r13,%r14,8),%r11
	movq %r15,%r13
	shrq $0x8,%r13
	movq (gcState+0x3C8)(%rip),%r10
	movb $0x1,0x0(%r10,%r13,1)
	movq %r11,0x0(%r15,%r14,8)
	incq %r14
	jmp loop_3771
.p2align 0x4
L_530951:
L_373262:
	movq $0xF47,0xFFFFFFFFFFFFFFF8(%r15)
	movq %r15,0x0(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530953:
L_373265:
	movq (globalObjptr+0x638)(%rip),%r15
	jmp L_373261
.p2align 0x4
L_530954:
L_373266:
	movq 0x10(%rbp),%r15
	movq %r15,0x0(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530955:
L_373267:
	movq (c_stackP+0x0)(%rip),%rsp
	movl $0x0,%r15d
	movl %r15d,%edx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x20,%rbp
	leaq (L_373268+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_collect
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373268
.p2align 0x4
.long 0x45B
L_373268:
	addq $0xFFFFFFFFFFFFFFE0,%rbp
	jmp L_373236
.p2align 0x4
L_530956:
L_373269:
	movq (c_stackP+0x0)(%rip),%rsp
	movl $0x0,%r15d
	movl %r15d,%edx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x20,%rbp
	leaq (L_373270+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_collect
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373270
.p2align 0x4
.long 0x45B
L_373270:
	addq $0xFFFFFFFFFFFFFFE0,%rbp
	jmp L_373232
.p2align 0x4
L_530957:
L_373271:
	movq (globalObjptr+0x640)(%rip),%r14
	movq $0xF47,0xFFFFFFFFFFFFFFF8(%r14)
	movq %r14,0x0(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.text
.p2align 0x4
.globl processEnabled_0
.hidden processEnabled_0
processEnabled_0:
L_373274:
	cmpq %rbp,(gcState+0x18)(%rip)
	jnb L_373275
L_373394:
	movq (c_stackP+0x0)(%rip),%rsp
	movl $0x0,%r15d
	movl %r15d,%edx
	xorq %rsi,%rsi
	leaq gcState(%rip),%r15
	movq %r15,%rdi
	xorq %rax,%rax
	addq $0x20,%rbp
	leaq (L_373395+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	movq %rbp,(gcState+0x10)(%rip)
	movq %r12,(gcState+0x0)(%rip)
	call GC_collect
	movq (gcState+0x0)(%rip),%r12
	movq (gcState+0x10)(%rip),%rbp
	jmp L_373395
.p2align 0x4
.long 0x4E8
L_373395:
	addq $0xFFFFFFFFFFFFFFE0,%rbp
L_373275:
	movq 0x8(%rbp),%r14
	movq 0xFFFFFFFFFFFFFFF0(%r14),%r15
	movl %r15d,%r14d
	movl %r14d,0x4(%rbp)
	movslq %r14d,%r13
	cmpq %r13,%r15
	jne L_530990
L_373278:
	xorl %ebx,%ebx
	xorl %ecx,%ecx
.p2align 0x4,,0x7
loop_3772:
	cmpl 0x4(%rbp),%ecx
	jnl L_530961
L_373390:
	movl %ecx,%r14d
	incl %r14d
	movslq %ecx,%r13
	cmpq %r15,%r13
	jnb L_530960
L_373392:
	incl %ebx
	jo L_530959
L_373393:
	movl %r14d,%ecx
	jmp loop_3772
.p2align 0x4
L_530959:
L_373285:
	movq $0x3,(globalObjptrNonRoot+0x0)(%rip)
	movq (gcState+0x560)(%rip),%rbp
	addq (gcState+0x20)(%rip),%rbp
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530960:
L_373282:
	movq $0x6,(globalObjptrNonRoot+0x0)(%rip)
	movq (gcState+0x560)(%rip),%rbp
	addq (gcState+0x20)(%rip),%rbp
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530961:
L_373279:
	movl $0x0,0x18(%rbp)
.p2align 0x4,,0x7
loop_3773:
	movl 0x18(%rbp),%r14d
	cmpl %ebx,%r14d
	je L_530965
L_373280:
	movslq %r14d,%r13
	cmpq %r15,%r13
	jnb L_373282
L_373283:
	movq 0x8(%rbp),%r11
	cmpb $0x3A,0x0(%r11,%r13,1)
	je L_530963
L_373284:
	incl %r14d
	jo L_373285
L_373286:
	movl %r14d,0x18(%rbp)
	jmp loop_3773
.p2align 0x4
L_530963:
L_373287:
	movl %r14d,%r15d
	shlq $0x1,%r15
	orq $0x1,%r15
	movq %r15,0x28(%rbp)
	movl $0x0,0x30(%rbp)
	movq 0x8(%rbp),%r15
	movq %r15,0x38(%rbp)
	addq $0x28,%rbp
	leaq (L_373288+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	jmp extract_0
.p2align 0x4
L_530965:
L_373389:
	movq 0x8(%rbp),%r15
parseId_0:
	movq 0x10(%rbp),%r14
.p2align 0x4,,0x7
loop_3775:
	movq 0x10(%r14),%r13
	movq 0x8(%r14),%r11
	movq 0x0(%r14),%r8
	cmpq %r8,%r15
	je L_530989
L_373304:
	movq 0xFFFFFFFFFFFFFFF0(%r15),%r10
	cmpq %r10,0xFFFFFFFFFFFFFFF0(%r8)
	jne L_530988
L_373356:
	xorq %r9,%r9
	movq %r8,%r14
.p2align 0x4,,0x7
vectorEqualLoop_278:
	cmpq %r9,%r10
	je L_530987
L_373357:
	movb 0x0(%r15,%r9,1),%r8b
	cmpb %r8b,0x0(%r14,%r9,1)
	jne L_530966
L_373359:
	incq %r9
	jmp vectorEqualLoop_278
.p2align 0x4
L_530966:
	movq %r10,%r14
L_373306:
	cmpq $0x1,%r13
	je L_530986
L_373307:
	movq 0xFFFFFFFFFFFFFFF8(%r13),%r11
	shrq $0x1,%r11
	cmpq $0x2492,%r11
	jne L_530985
L_373308:
	movq 0x0(%r13),%r11
	movq %r11,%r13
.p2align 0x4,,0x7
loop_3776:
	movq 0x10(%r13),%r11
	movq 0x8(%r13),%r10
	movq 0x0(%r13),%r8
	cmpq %r15,%r8
	je L_530984
L_373309:
	cmpq 0xFFFFFFFFFFFFFFF0(%r8),%r14
	jne L_373311
L_373348:
	xorq %r9,%r9
	movq %r8,%r13
.p2align 0x4,,0x7
vectorEqualLoop_277:
	cmpq %r14,%r9
	je L_530982
L_373349:
	movb 0x0(%r15,%r9,1),%r8b
	cmpb %r8b,0x0(%r13,%r9,1)
	jne L_530967
L_373351:
	incq %r9
	jmp vectorEqualLoop_277
.p2align 0x4
L_530967:
L_373311:
	movq 0xFFFFFFFFFFFFFFF8(%r11),%r10
	shrq $0x1,%r10
	cmpq $0x2495,%r10
	je L_530973
	cmpq $0x2496,%r10
	je L_530972
L_373312:
	movq 0x8(%r11),%r9
	movq 0x0(%r11),%r13
	cmpq (globalObjptr+0xBD50)(%rip),%r15
	je L_530971
L_373313:
	cmpq $0xC,%r14
	jne loop_3776
L_373315:
	xorq %r10,%r10
	movq %r9,%r11
.p2align 0x4,,0x7
vectorEqualLoop_273:
	cmpq %r14,%r10
	je L_530969
L_373316:
	movq (globalObjptr+0xBD50)(%rip),%r8
	movb 0x0(%r8,%r10,1),%r9b
	cmpb %r9b,0x0(%r15,%r10,1)
	jne loop_3776
L_373318:
	incq %r10
	jmp vectorEqualLoop_273
.p2align 0x4
L_530969:
L_373319:
	movq %r11,%r15
L_373320:
	movq 0x10(%r15),%r14
	movl 0x0(%rbp),%r13d
	movl %r13d,0x0(%r14)
	movb $0x0,0x0(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530971:
L_373321:
	movq %r9,%r15
	jmp L_373320
.p2align 0x4
L_530972:
L_373347:
	movq 0x0(%r11),%r13
	jmp loop_3776
.p2align 0x4
L_530973:
L_373322:
	movq 0x18(%r11),%rsp
	movq 0x10(%r11),%r10
	movq 0x8(%r11),%r9
	movq 0x0(%r11),%r13
	cmpq (globalObjptr+0xBD38)(%rip),%r15
	je L_530981
L_373323:
	cmpq $0x15,%r14
	jne vectorEqual_100
L_373341:
	xorq %r8,%r8
	movq %rsp,%r11
.p2align 0x4,,0x7
vectorEqualLoop_276:
	cmpq %r8,%r14
	je L_530980
L_373342:
	movq (globalObjptr+0xBD38)(%rip),%rsi
	movb 0x0(%rsi,%r8,1),%spl
	cmpb %spl,0x0(%r15,%r8,1)
	jne vectorEqual_296
L_373344:
	incq %r8
	jmp vectorEqualLoop_276
.p2align 0x4
vectorEqual_296:
vectorEqual_100:
	cmpq %r15,(globalObjptr+0xBD30)(%rip)
	je L_530979
L_373325:
	cmpq $0x6,%r14
	jne vectorEqual_101
L_373335:
	xorq %r11,%r11
.p2align 0x4,,0x7
vectorEqualLoop_275:
	cmpq %r11,%r14
	je L_530978
L_373336:
	movq (globalObjptr+0xBD30)(%rip),%r8
	movb 0x0(%r15,%r11,1),%spl
	cmpb %spl,0x0(%r8,%r11,1)
	jne vectorEqual_297
L_373338:
	incq %r11
	jmp vectorEqualLoop_275
.p2align 0x4
vectorEqual_297:
vectorEqual_101:
	cmpq (globalObjptr+0xBD20)(%rip),%r15
	je L_530977
L_373327:
	cmpq $0x9,%r14
	jne L_530976
L_373329:
	xorq %r11,%r11
.p2align 0x4,,0x7
vectorEqualLoop_274:
	cmpq %r11,%r14
	je L_530975
L_373330:
	movq (globalObjptr+0xBD20)(%rip),%r8
	movb 0x0(%r8,%r11,1),%r10b
	cmpb %r10b,0x0(%r15,%r11,1)
	jne L_530974
L_373332:
	incq %r11
	jmp vectorEqualLoop_274
.p2align 0x4
L_530974:
L_373331:
	movq %r13,%r14
	jmp loop_3775
.p2align 0x4
L_530975:
L_373333:
	movq %r9,%r15
	jmp L_373320
.p2align 0x4
L_530976:
L_373328:
	movq %r13,%r14
	jmp loop_3775
.p2align 0x4
L_530977:
L_373334:
	movq %r9,%r15
	jmp L_373320
.p2align 0x4
L_530978:
L_373339:
	movq %r10,%r15
	jmp L_373320
.p2align 0x4
L_530979:
L_373340:
	movq %r10,%r15
	jmp L_373320
.p2align 0x4
L_530980:
L_373345:
	movq %r11,%r15
	jmp L_373320
.p2align 0x4
L_530981:
L_373346:
	movq %rsp,%r15
	jmp L_373320
.p2align 0x4
L_530982:
L_373352:
	movq %r10,%r15
	jmp L_373320
.p2align 0x4
L_530984:
L_373353:
	movq %r10,%r15
	jmp L_373320
.p2align 0x4
L_530985:
L_373354:
	movq 0x0(%r13),%r14
	jmp loop_3775
.p2align 0x4
L_530986:
L_373298:
	movb $0x1,0x0(%rbp)
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
L_530987:
L_373360:
	movq %r11,%r15
	jmp L_373320
.p2align 0x4
L_530988:
	movq %r10,%r14
	jmp L_373306
.p2align 0x4
L_530989:
L_373361:
	movq %r11,%r15
	jmp L_373320
.p2align 0x4
L_530990:
L_373277:
	movq (globalObjptr+0x4D8)(%rip),%r15
	movq %r15,(globalObjptrNonRoot+0x0)(%rip)
	movq (gcState+0x560)(%rip),%rbp
	addq (gcState+0x20)(%rip),%rbp
	jmp *0xFFFFFFFFFFFFFFF8(%rbp)
.p2align 0x4
.long 0x4F4
L_373288:
	addq $0xFFFFFFFFFFFFFFD8,%rbp
	movq 0x28(%rbp),%r14
	movq %r14,0x20(%rbp)
	movq 0xFFFFFFFFFFFFFFF0(%r14),%r15
	movl %r15d,%ecx
	movslq %ecx,%r14
	cmpq %r15,%r14
	jne L_373277
L_373290:
	xorl %ebx,%ebx
.p2align 0x4,,0x7
loop_3774:
	cmpl %ecx,%ebx
	jnl L_531003
L_373363:
	movslq %ebx,%r14
	cmpq %r15,%r14
	jnb L_373282
L_373365:
	movq 0x20(%rbp),%r13
	movb 0x0(%r13,%r14,1),%r11b
	cmpb $0xD,%r11b
	ja L_531000
L_373366:
	cmpb $0x9,%r11b
	jb L_530992
L_373368:
	incl %ebx
	jmp loop_3774
.p2align 0x4
L_530992:
L_373370:
	decl %ecx
.p2align 0x4,,0x7
loop_3777:
	movslq %ecx,%r14
	cmpq %r15,%r14
	jnb L_373282
L_373372:
	movq 0x20(%rbp),%r13
	movb 0x0(%r13,%r14,1),%r11b
	cmpl %ecx,%ebx
	jnl L_530998
L_373375:
	cmpb $0xD,%r11b
	ja L_530996
L_373376:
	cmpb $0x9,%r11b
	jb L_530993
L_373378:
	decl %ecx
	jmp loop_3777
.p2align 0x4
L_530993:
L_373380:
	subl %ebx,%ecx
	jo L_373285
L_373381:
	incl %ecx
	jo L_373285
L_373382:
	movl %ebx,0x30(%rbp)
	movl %ecx,%r15d
	shlq $0x1,%r15
	orq $0x1,%r15
	movq %r15,0x28(%rbp)
	movq 0x20(%rbp),%r15
	movq %r15,0x38(%rbp)
	addq $0x28,%rbp
	leaq (L_373374+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	jmp extract_0
.p2align 0x4
L_530996:
L_373383:
	cmpb $0x20,%r11b
	jne L_373380
	jmp L_373378
.p2align 0x4
L_530998:
L_373373:
	movzbq %r11b,%r15
	shlq $0x4,%r15
	orq $0x9,%r15
	movq %r15,0x28(%rbp)
	movl $0x1,0x30(%rbp)
	addq $0x28,%rbp
	leaq (L_373374+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	jmp unfoldi_0
.p2align 0x4
L_531000:
L_373386:
	cmpb $0x20,%r11b
	jne L_373370
	jmp L_373368
.p2align 0x4
L_531003:
L_373292:
	movl 0x18(%rbp),%r15d
	incl %r15d
	jo L_373285
L_373293:
	movl 0x4(%rbp),%r14d
	subl %r15d,%r14d
	jo L_373285
L_373294:
	movl %r15d,0x38(%rbp)
	movl %r14d,%r15d
	shlq $0x1,%r15
	orq $0x1,%r15
	movq %r15,0x30(%rbp)
	movq 0x8(%rbp),%r15
	movq %r15,0x40(%rbp)
	addq $0x30,%rbp
	leaq (L_373295+0x0)(%rip),%r15
	movq %r15,0xFFFFFFFFFFFFFFF8(%rbp)
	jmp extract_0
.p2align 0x4
.long 0x4F4
L_373374:
	addq $0xFFFFFFFFFFFFFFD8,%rbp
	movq 0x28(%rbp),%r15
	movq %r15,0x20(%rbp)
	jmp L_373292
.p2align 0x4
.long 0x2
L_373295:
	addq $0xFFFFFFFFFFFFFFD0,%rbp
	movq 0x30(%rbp),%r13
	movq %r13,0x8(%rbp)
	movq 0x20(%rbp),%r13
	cmpq %r13,(globalObjptr+0x10C18)(%rip)
	je L_531010
L_373296:
	movq 0xFFFFFFFFFFFFFFF0(%r13),%r15
	cmpq $0x5,%r15
	jne L_373298
L_373299:
	xorq %r14,%r14
.p2align 0x4,,0x7
vectorEqualLoop_272:
	cmpq %r15,%r14
	je L_531008
L_373300:
	movq 0x20(%rbp),%r13
	movq (globalObjptr+0x10C18)(%rip),%r10
	movb 0x0(%r10,%r14,1),%r11b
	cmpb %r11b,0x0(%r13,%r14,1)
	jne L_373298
L_373302:
	incq %r14
	jmp vectorEqualLoop_272
.p2align 0x4
L_531008:
L_373303:
	movq 0x8(%rbp),%r15
	jmp parseId_0
.p2align 0x4
L_531010:
L_373362:
	movq 0x8(%rbp),%r15
	jmp parseId_0
